# Generated by Django 3.2.9 on 2021-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000)),
                ('title', models.CharField(max_length=500)),
                ('guid', models.CharField(max_length=5255)),
                ('link', models.CharField(max_length=255)),
                ('published', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
    ]
